# site settings
title:
subtitle:
email: shiye2015@u.northwestern.edu
description: Ph.D. Student, <br /> Center for Interdisciplinary Exploration and Research in Astrophysics (CIERA), <br /> Department of Physics and Astronomy, <br /> Northwestern University
baseurl: #"/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Claire Ye
street_address: 1800 Sherman Avenue
city: Evanston
state: IL
zip_code: 60208
country: United States of America
phone: (847) 868-4381

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:  
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url: 
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
